### PR TITLE
JDK11 support

### PR DESCRIPTION
**Pull request by DMLoy**
This would make this a Java 11 project. 

`test` and `spring-boot:run` all work with what I've tested.  

https://github.com/jonashackt/spring-boot-vuejs/issues/17 was the inspiration. But JDK11 is LTS.

### CODE REVIEW

**Comment by mgh87** [comment]
Due to the reformatting the differences are really hard to spot.
Is there a reason, why you would downgrade <build-plugin.jacoco.version> from 0.8.2 to 0.8.1?

**Comment by mgh87** [comment]
Thanks for pointing out the whitespace filter. (Wasn't aware of this feature).
Have you thought about profiles and jdk activations to create a dynamic binding based on the jdk set within the shells environment?

That would keep it stable for 8 and 11, since 11 is not that wide spread yet.

**Comment by mgh87** [comment]
https://github.com/mgh87/spring-boot-vuejs/tree/java11_support

Here would be my change to a profile approach. GitHub, didn't let me create a pull request to your repository, for whatever reason.

**Comment by DMLoy** [comment]
@jonashackt @mgh87 comments welcome!

**Comment by jonashackt** [comment]
Hey @DMLoy & @mgh87 - sorry for the delay, but I was really busy - and didn't want to tackle issues, that would have been solved in the future (like extra surefire configuration and so on). Now with https://github.com/jonashackt/spring-boot-vuejs/pull/45 - and just using TravisCI building on all major JDKs, this should be done right now. If you'd like to test, it would be great. Closing this now.

**Pull request closed without merging**
